### ISSUE TITLE
URL matchmaking for redirect should allow GET parameters

### ISSUE THREAD

**Issue by troeger** [CSCfi/shibboleth-idp-oidc-extension#37]
We are testing the OIDC extension with a Django application that uses Python Social for OAuth2 authentication. 

We ended in the following log message:

```
==> logs/idp-warn.log <==
2020-01-06 16:36:04,689 - ERROR [org.geant.idpextension.oidc.profile.impl.ValidateRedirectURI:115] - Profile Action ValidateRedirectURI: Redirection URI http://localhost:8000/social/complete/beuthtest/?redirect_state=o2eOmbd3CL3MG1jKy44t20R94JMv8sFp not matching any of the registered Redirection URIs [http://localhost:8000/social/complete/beuthtest/] 
```

The source code of _ValidateRedirectURI.java_ looks like there is a match making on the complete URL, even if it contains a query string. This does not seem to be correct.

**Comment by hjmikkon** [comment]
The [OIDC core section 3.1.2.1](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) defines the following. For redirect_uri: "This URI MUST exactly match one of the Redirection URI values for the Client pre-registered at the OpenID Provider".

So, Python Social for OAuth2 doesn't seem to be following the OIDC specification. Both OIDC and OAuth2 specs mention a recommended parameter called _state_ that can be used for maintaining the state between the request and the callback. This *redirect_state* looks something similar (?), but is not standardized.

**Comment by troeger** [comment]
Agreed. Python Social uses the "redirect_state" parameter by default when you implement your own OAuth2 authentication backend:

https://github.com/python-social-auth/social-core/blob/master/social_core/backends/oauth.py

This seems to be a (strange) compatibility feature for providers not implementing the standardized "state" parameter. 

Setting _REDIRECT_STATE = False_ in my authentication backend changes the parameter name accordingly, so now the called URL looks like this:

```
https://.../idp/profile/oidc/authorize?client_id=aaa&redirect_uri=http://localhost:8000/social/complete/shiboidctest/&state=o2eOmbd3CL3MG1jKy44t20R94JMv8sFp&response_type=code&scope=openid
```
The problem, however, remains the same. The redirect URI still does not match, even though the standardized _state_ parameter is now used.

**Comment by hjmikkon** [comment]
What is the log-line now? I mean, in your latest quote, you seemed to be using the following redirect_uri:

http://localhost:8000/social/complete/shiboidctest/

It's not matching the trusted redirect_uri in your first message, which was:

http://localhost:8000/social/complete/beuthtest/

**Comment by troeger** [comment]
This was another test system.

**Comment by hjmikkon** [comment]
Can you please share the current line(s) from idp-warn.log regarding class org.geant.idpextension.oidc.profile.impl.ValidateRedirectURI?

**Comment by cultcom** [comment]
Ok, I tried it again and it seems to work now so far. But I noted something else:

The JWK returned to the RP does not contain a value for "alg" to identify the used algorithm. I am not quite sure if I should set this fixed in "credentials/idp-encryption-rsa.jwk" or if that should be added dynamically by the plugin.

Currently the pyhton-jose implementation does not work without having "alg" set.

**Comment by hjmikkon** [comment]
Apologies for the delay in replying to this thread.

You're right: the KeySet-flow doesn't set the alg -value for the keys. How I see it, it shouldn't set them because the same key may potentially be used with multiple algorithms. Also the spec says that alg is optional.

However, you can meet this special RP requirement by storing the Keyset into a file, publishing the file in a Web server, and pointing your RP to that file: the contents of your current key-configuration can be fetched from https://your_server/idp/profile/oidc/keyset - Copy-paste this output into a file, modify the keys to have the desired alg -values and publish the keyset in a Web-server. If the RP obtains the JWKS url from the openid-configuration, you then need update the jwks_uri claim in your OP configuration to point to this new JWKS url (by default, the configuration file exists in IDP_HOME/static/.well-known/openid-configuration).
