### ISSUE TITLE
Unable to use introspection endpoint

### ISSUE THREAD

**Issue by psagne** [CSCfi/shibboleth-idp-oidc-extension#42]
I can't find how to use the introspection endpoint.
The documentation is unclear about how to configure the access policy for this endpoint.
From what I found, it seems that i have to call it as a POST method, with "token=OIDC_TOKEN" as POST data.
But I always get an error message saying that clientId cannont be null.
I also tried to pass an "Authorization: Bearer xxx" with the same token or another one, but I can't find a call configuration which anything else than an error.
What are the required parameters to call this endpoint, and what configuration is required?

**Comment by hjmikkon** [comment]
Have you looked at this Wiki page: https://github.com/CSCfi/shibboleth-idp-oidc-extension/wiki/OAUTH2.Introspection ?

In short, the idea of the introspection endpoint is to provide information about access token to authorized clients. So, the clients also need to authenticate themselves to the endpoint, that's why you get error message saying that clientId cannot be null.

By default, the client authentication method is client_secret_basic, so you'd need to build the Authorization header as instructed e.g. [here](https://en.wikipedia.org/wiki/Basic_access_authentication)

**Comment by psagne** [comment]
Thank you for the reply. I figured it out by the time.
What confused me is that i had set "token_endpoint_auth_method": "client_secret_post" in my client configuration, and it applied to the introspection endpoint as well.
Once i figured it out, i just had to put client_id and client_secret in the post data, along with the token.
